### ISSUE TITLE
factor out hard-coded resource names

### ISSUE THREAD

**Issue by davidstanke** [GoogleCloudPlatform/cloudbuild-integration-testing#33]
There are scattered hard-coded project names, cluster names, zones. Let's pull those out so the build can be run in any project without code changes.

**Comment by davidstanke** [comment]
Hey Guille! Excellent progress. I'm not sure if there's more to do here, but I feel like it's in good shape, so I'll punt this issue to v0.1.1 and tag release 0.1

**Comment by murog** [comment]
Fixed in #43
