### ISSUE TITLE
Tag container images by build

### ISSUE THREAD

**Issue by davidstanke** [GoogleCloudPlatform/cloudbuild-integration-testing#47]
Currently, we tag all images as 'web','db' ... these get pushed to registry as 'web:latest','db:latest'. This happens even if the rest of the build fails. As a result, we have the potential for collision and version drift: one test might pick up the containers built by another. Also, a job deploying to prod might grab a version that's actually no good.

We should tag the images with build-specific tags and push those specific images to the test environment.

(Possibly: at the end of the build—on success—re-tag as "latest")

**Comment by murog** [comment]
Issue was opened while in development, closing for now while project is in maintenance mode.
