### ISSUE TITLE
Q: Why is cluster name set to `staging` if creating a new temp cluster with name test-<date> ?

### ISSUE THREAD

**Issue by naseemkullah** [GoogleCloudPlatform/cloudbuild-integration-testing#63]
https://github.com/GoogleCloudPlatform/cloudbuild-integration-testing/blob/3c2155ad68add85a8775d30ac16b20719f230db7/cloudbuild.gke-per-test.yaml#L145

**Comment by murog** [comment]
Thanks for raising this, seems like this was left over from a previous example.  The example creates a new cluster and references that in later build steps.   Removed this reference in #66
