### ISSUE TITLE
Try alternative k8s implementations for GCE VM

### ISSUE THREAD

**Issue by davidstanke** [GoogleCloudPlatform/cloudbuild-integration-testing#9]
MiniKube and MicroK8s are both intended as lightweight, single-node K8s implementations. Might they be faster/easier than the full thing? Would they provide appropriate fidelity? (ie. how likely is it that a test against MiniKube will succeed, but then the app fails on Kubernetes? Obviously, that's not _supposed_ to happen.)

**Comment by davidstanke** [comment]
Also: Kind (Kubernetes-in-Docker)

**Comment by davidstanke** [comment]
Also, k3s

**Comment by murog** [comment]
Issue was opened while in development, closing for now while project is in maintenance mode.
